### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by dbvcode** [Reiryoku-Technologies/Mida-cTrader#13]
`npm i @reiryoku/mida@latest`

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: tradeguardian@0.0.0
npm WARN Found: @reiryoku/mida@5.0.1
npm WARN node_modules/@reiryoku/mida
npm WARN   peer @reiryoku/mida@"^5.0.1" from @reiryoku/mida-ctrader@2.1.0
npm WARN   node_modules/@reiryoku/mida-ctrader
npm WARN     @reiryoku/mida-ctrader@"^2.1.0" from the root project
npm WARN   1 more (the root project)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @reiryoku/mida@"^5.0.1" from @reiryoku/mida-ctrader@2.1.0
npm WARN node_modules/@reiryoku/mida-ctrader
npm WARN   @reiryoku/mida-ctrader@"^2.1.0" from the root project

I don't think it's a big deal but regarding https://github.com/Reiryoku-Technologies/Mida/issues/25 I realized I had mida 5.0.1 installed and I could not find `composePeriods`

**Comment by dbvcode** [comment]
Unfortunately this seems to be a big deal as it breaks the build

```
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/dbv/Code/tg/node_modules/@reiryoku/mida-ctrader/src/core/brokers/ctrader/orders/CTraderBrokerOrder.ts:12:41)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.Module._load (/home/dbv/Code/tg/packages/node/src/executors/node/node-with-require-overrides.ts:16:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.Hook._require.Module.require (/home/dbv/Code/tg/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/dbv/Code/tg/node_modules/@reiryoku/mida-ctrader/src/core/brokers/ctrader/CTraderBrokerAccount.ts:32:1)
```

**Comment by Vasile-Peste** [comment]
Hi, yes you are right the latest Mida cTrader version is not compatible with Mida 7.0, but I'm already working on this! Should be released by end of this week. I will keep this issue open until everything is working as expected.

**Comment by Vasile-Peste** [comment]
Hey, `Mida cTrader 3.0.0` is out (https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v3.0.0) and fully supports the latest Mida version, let me know if everything works as expected for you.

**Comment by dbvcode** [comment]
Hi,
I have updated to the latest versions of Mida and Mida-cTrader but the `Mida.login` for the cTrader account fails:

```
Error: 
    at Function.login (/home/dbv/tg/node_modules/@reiryoku/mida/src/core/platforms/MidaTradingPlatform.ts:76:19)
    at Function.login (/home/dbv/tg/node_modules/@reiryoku/mida/src/core/Mida.ts:65:36)
    at /home/dbv/tg/dist/apps/backfill/pepperstone/webpack:/tg/apps/backfill/pepperstone/src/app/clients/exchangeAccounts.ts:27:30
    at Generator.next (<anonymous>)
    at /home/dbv/tg/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/home/dbv/tg/node_modules/tslib/tslib.js:113:16)
    at initPepperstoneGeneric (/home/dbv/tg/dist/apps/backfill/pepperstone/main.js:29:34)
    at /home/dbv/tg/dist/apps/backfill/pepperstone/webpack:/tg/apps/backfill/pepperstone/src/app/services/tasksService.ts:23:31
    at Generator.next (<anonymous>)
```

**Comment by Vasile-Peste** [comment]
I think that you are using an old version of Mida, this is how you import the plugin now
```javascript
import { Mida, } from "@reiryoku/mida";
import { CTraderPlugin, } from "@reiryoku/mida-ctrader";

Mida.use(new CTraderPlugin());
```

**Comment by dbvcode** [comment]
Awesome! Works like a charm!
Thank you very much!
